### post offer success
POST http://localhost:3000/api/offers HTTP/1.1
content-type: application/json

{
  "ticket-name": "Куплю приставку Sony Playstation 5.",
  "action": "offer",
  "comment": "Заберу сам 🚚... Только в рабочем состоянии 🙏🏽.",
  "price": 5151,
  "avatar": "avatar.jpg",
  "category": ["Разное", "Игры"]
}

### check new offer added
GET http://localhost:3000/api/offers/oKrZ_K HTTP/1.1

### delete added offer
DELETE http://localhost:3000/api/offers/oKrZ_K HTTP/1.1

### check added offer deleted
GET http://localhost:3000/api/offers/oKrZ_K HTTP/1.1

### post offer failed - missed offer ticket-name field
POST http://localhost:3000/api/offers/ HTTP/1.1
content-type: application/json

{
  "name": "Куплю приставку Sony Playstation 5.",
  "action": "offer",
  "comment": "Заберу сам 🚚... Только в рабочем состоянии 🙏🏽.",
  "price": 5151,
  "avatar": "avatar.jpg",
  "category": ["Разное", "Игры"]
}

### post offer failed - incorrect required fields count
POST http://localhost:3000/api/offers/ HTTP/1.1
content-type: application/json

{
  "ticket-name": "Куплю приставку Sony Playstation 5.",
  "comment": "Заберу сам 🚚... Только в рабочем состоянии 🙏🏽.",
  "price": 5151,
  "avatar": "avatar.jpg",
  "category": ["Разное", "Игры"]
}

### post offer failed - incorrect required fields count
POST http://localhost:3000/api/offers/ HTTP/1.1
content-type: application/json

{}
