### add new offer
POST http://localhost:3000/api/offers HTTP/1.1
content-type: application/json

{
  "ticket-name": "Куплю приставку Sony Playstation 5.",
  "action": "offer",
  "comment": "Заберу сам 🚚... Только в рабочем состоянии 🙏🏽.",
  "price": 5151,
  "avatar": "avatar.jpg",
  "category": ["Разное", "Игры"]
}

### check added offer
GET http://localhost:3000/api/offers/WGVfLm HTTP/1.1

### delete added offer
DELETE http://localhost:3000/api/offers/Y1R6W2 HTTP/1.1

### check added offer deleted
GET http://localhost:3000/api/offers/Y1R6W2 HTTP/1.1

### delete offer failed - not found
DELETE http://localhost:3000/api/offers/r7EdPb HTTP/1.1
