### get search success - found
GET http://localhost:3000/api/search?query=куплю HTTP/1.1

### get search success - not found
GET http://localhost:3000/api/search?query=аппарат HTTP/1.1

### get search failed - empty query
GET http://localhost:3000/api/search?query= HTTP/1.1
