### add new offer
POST http://localhost:3000/api/offers HTTP/1.1
content-type: application/json

{
  "ticket-name": "Куплю приставку Sony Playstation 5.",
  "action": "offer",
  "comment": "Заберу сам 🚚... Только в рабочем состоянии 🙏🏽.",
  "price": 5151,
  "avatar": "avatar.jpg",
  "category": ["Разное", "Игры"]
}

### check new offer - paste offer id from previuos request
GET http://localhost:3000/api/offers/1Glzon HTTP/1.1

### put offer success - paste offer id from previuos request
PUT http://localhost:3000/api/offers/1Glzon HTTP/1.1
content-type: application/json

{
  "ticket-name": "Куплю VR-камеру для съемки",
  "price": 5000
}

### check put success - paste offer id from previuos request
GET http://localhost:3000/api/offers/1Glzon HTTP/1.1

### delete offer - paste id from previous request
DELETE http://localhost:3000/api/offers/1Glzon HTTP/1.1

### check deleted offer - paste offer id from previuos request
GET http://localhost:3000/api/offers/1Glzon HTTP/1.1

### put offer failed
PUT http://localhost:3000/api/offers/OGPGDP HTTP/1.1
content-type: application/json

{
  "name": "Куплю любимые книги Харуки Мураками.",
  "price": 3000
}

### put offer failed - wrong field - name
PUT http://localhost:3000/api/offers/OGPGDP HTTP/1.1
content-type: application/json

{}
